media: assets
content:
  - name: pages
    label: Pages
    type: collection
    path: docs

    fields:
      - name: title
        label: Title
        type: string

      - name: description
        label: Description
        type: string

      - name: nav_order
        label: nav_order
        type: number

      - name: parent
        label: parent
        type: string

      - name: body
        label: Content
        type: rich-text      